# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""The 5B filter experiment: two arms (control = 5B prefix pool of the trained longmino
corpus; filtered_k2 = the term screen's K=2 survivors), each one job of 298 iterations that
never resumes, saving every 30 iterations so checkpoints exist at 30 / 90 / 298 (0.5 / 1.5 /
5.0B tokens, log-spaced; the others are deleted after the run). Each config is the 20B
longmino config with exactly the stated keys changed. Generated by make_5b_configs.py; these
tests pin what it must produce.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
import yaml
from megatron.bridge.recipes.nemotronh.nemotron_3_nano import nemotron_3_nano_pretrain_config
from omegaconf import OmegaConf

from tests.unit_tests.campaign_config import (
    assert_blend_is_well_formed,
    assert_only_these_fields_differ,
    merge_onto_recipe,
)

REPO = Path(__file__).resolve().parents[2]
ARM = REPO / "configs" / "control_pretraining" / "longmino_cpt"
BASE = ARM / "nemotron_nano_30b_baseline_longmino_cpt.yaml"
ARMS = ("control", "filtered_k2")
TRAIN_ITERS = 298
SAVE_INTERVAL = 30
KEEP = (30, 90, 298)
TOKENS_PER_ITER = 512 * 32768
OUR_ROOTS = ("/projects/a5k/public/data_cwtice.a5k/data/",)
POOLS = Path("/projects/a5k/public/data_cwtice.a5k/data/longmino_cpt/pools_5b.json")
ALLOWED_DIVERGENCE = {
    "dataset.data_path",
    "dataset.path_to_cache",
    "train.train_iters",
    "scheduler.lr_wsd_decay_iters",
    "checkpoint.load",
    "checkpoint.save",
    "checkpoint.save_interval",
    "logger.wandb_exp_name",
}


def cfg_path(arm: str) -> Path:
    return ARM / f"nemotron_nano_30b_baseline_longmino_5b_{arm}.yaml"


pytestmark = pytest.mark.skipif(
    not all(cfg_path(a).exists() for a in ARMS),
    reason="5B configs not generated yet (make_5b_configs.py)",
)


def _merged(path: Path):
    return merge_onto_recipe(path, nemotron_3_nano_pretrain_config)


@pytest.fixture(scope="module")
def base_merged():
    return _merged(BASE)


@pytest.fixture(scope="module", params=list(ARMS))
def arm(request):
    return request.param


@pytest.fixture(scope="module")
def merged(arm):
    return _merged(cfg_path(arm))


@pytest.fixture(scope="module")
def raw(arm):
    return OmegaConf.load(cfg_path(arm))


class TestStatedDiffFromTheTwentyBillionConfig:
    def test_exactly_the_stated_fields_differ(self, merged, base_merged, arm):
        assert_only_these_fields_differ(merged, base_merged, ALLOWED_DIVERGENCE, f"longmino_5b_{arm}")

    def test_budget_is_five_billion_tokens(self, merged):
        assert merged.train.train_iters == TRAIN_ITERS
        assert abs(TRAIN_ITERS * TOKENS_PER_ITER - 5e9) / 5e9 < 0.001

    def test_anneal_spans_the_run(self, merged, raw):
        assert raw.scheduler.lr_wsd_decay_iters == TRAIN_ITERS == merged.train.train_iters

    def test_no_segment_stop_and_no_resume(self, merged):
        assert merged.train.exit_interval is None

    def test_saves_hit_the_kept_iterations(self, merged):
        assert merged.checkpoint.save_interval == SAVE_INTERVAL
        assert merged.checkpoint.most_recent_k == -1
        saved = {i for i in range(SAVE_INTERVAL, TRAIN_ITERS + 1, SAVE_INTERVAL)} | {TRAIN_ITERS}
        assert set(KEEP) <= saved
        tokens = [i * TOKENS_PER_ITER for i in KEEP]
        ratios = [b / a for a, b in zip(tokens, tokens[1:], strict=False)]
        assert all(2.9 < r < 3.4 for r in ratios), ratios

    def test_load_and_save_are_the_arms_own_directory(self, merged, base_merged, arm):
        assert merged.checkpoint.load == merged.checkpoint.save
        assert merged.checkpoint.load.endswith(f"longmino_5b_{arm}")
        assert merged.checkpoint.load != base_merged.checkpoint.save
        assert merged.checkpoint.pretrained_checkpoint == base_merged.checkpoint.pretrained_checkpoint

    def test_index_cache_is_the_arms_own(self, raw, base_merged, arm):
        assert raw.dataset.path_to_cache.endswith(f"longmino_5b_{arm}")
        assert raw.dataset.path_to_cache != base_merged.dataset.path_to_cache
        assert raw.dataset.path_to_cache.startswith("/projects/a5k/public/data_cwtice.a5k/")

    def test_blend_is_well_formed_in_our_tree(self, raw):
        assert_blend_is_well_formed(raw.dataset.data_path, "longmino_5b", roots=OUR_ROOTS)

    def test_blend_names_the_arms_pool(self, raw, arm):
        pool = "pool5b_control" if arm == "control" else "pool5b_filtered_k2"
        prefixes = raw.dataset.data_path[1::2]
        assert all(f"/longmino_cpt/{pool}/" in p for p in prefixes), prefixes


class TestSchedule:
    def test_scheduler_hits_its_floor_at_the_final_save(self):
        import torch
        from megatron.core.optimizer_param_scheduler import OptimizerParamScheduler

        m = _merged(cfg_path("control"))
        raw3 = OmegaConf.load(cfg_path("control"))
        iters, warmup, wd = m.train.train_iters, m.scheduler.lr_warmup_iters, m.optimizer.weight_decay
        sch = OptimizerParamScheduler(
            optimizer=torch.optim.AdamW([torch.nn.Parameter(torch.zeros(1))], lr=m.optimizer.lr),
            init_lr=0.0, max_lr=m.optimizer.lr, min_lr=m.optimizer.min_lr, lr_warmup_steps=warmup,
            lr_decay_steps=iters, lr_decay_style=m.scheduler.lr_decay_style, start_wd=wd, end_wd=wd,
            wd_incr_steps=iters, wd_incr_style="constant", wsd_decay_steps=raw3.scheduler.lr_wsd_decay_iters,
            lr_wsd_decay_style=m.scheduler.lr_wsd_decay_style,
        )

        def lr_at(step):
            sch.num_steps = step
            return sch.get_lr({})

        assert lr_at(warmup) == pytest.approx(m.optimizer.lr)
        assert lr_at(iters) == pytest.approx(m.optimizer.min_lr)
        # the 0.5B save sits inside the warmup, the 1.5B save just before the peak
        assert lr_at(30) < lr_at(90) <= m.optimizer.lr


@pytest.mark.skipif(not POOLS.exists(), reason="pools not built")
class TestBlendMatchesThePools:
    @pytest.mark.parametrize("arm", ARMS)
    def test_weights_are_token_proportional_to_the_pool(self, arm):
        acct = json.loads(POOLS.read_text())["filtered" if arm == "filtered_k2" else "control"]
        fams = {k: v["tokens"] for k, v in acct.items() if not k.startswith("_")}
        tot = sum(fams.values())
        raw = OmegaConf.load(cfg_path(arm))
        got = {Path(p).parent.name: w for w, p in zip(raw.dataset.data_path[::2], raw.dataset.data_path[1::2], strict=True)}
        assert set(got) == set(fams)
        for fam, tokens in fams.items():
            assert abs(got[fam] - tokens / tot) < 2e-6, fam
        assert abs(sum(got.values()) - 1.0) < 1e-6

    def test_filtered_pool_allows_at_most_two_epochs(self):
        acct = json.loads(POOLS.read_text())["filtered"]
        assert acct["_total_tokens"] >= 2.5e9 * 0.98, acct["_total_tokens"]
