#!/usr/bin/env python3
"""Generate the six training configs of the 5B filter experiment from the 20B longmino CPT
config: two arms (control = 5B unfiltered prefix pool; filtered_k2 = term-screen survivors,
K=2) x three chained segments that stop at iterations 30 / 94 / 298 (0.5 / 1.6 / 5.0B tokens,
log-spaced) so each stop leaves a checkpoint.

Every segment of an arm is the same run: train_iters 298, the midtrain hyperparameters
verbatim, lr_wsd_decay_iters 298 (the anneal spans the run), save_interval 298, one
load == save directory. Segments differ only in train.exit_interval (30, 94, none): Megatron
saves and exits when iteration % exit_interval == 0, and the third segment saves at 298 by
save_interval. The optimizer scheduler is therefore identical in every segment and resumes
without overrides. Data: dataset.data_path is the token-proportional blend over the pool's
families (pools_5b.json), path_to_cache and checkpoint dirs are the arm's own.

    python make_5b_configs.py [--pools /projects/.../longmino_cpt/pools_5b.json]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
BASE = HERE / "nemotron_nano_30b_baseline_longmino_cpt.yaml"
CKPT_ROOT = "/projects/a5k/public/data_cwtice.a5k/checkpoints/megatron/control_pretraining"
CACHE_ROOT = "/projects/a5k/public/data_cwtice.a5k/gpt_index_cache"
POOL_ROOT = "/projects/a5k/public/data_cwtice.a5k/data/longmino_cpt"
ARMS = {"control": "pool5b_control", "filtered_k2": "pool5b_filtered_k2"}
SEGMENTS = [(1, 30), (2, 94), (3, None)]
TRAIN_ITERS = 298


def blend(acct: dict) -> list:
    fams = {k: v for k, v in acct.items() if not k.startswith("_")}
    tot = sum(v["tokens"] for v in fams.values())
    out: list = []
    for fam, v in sorted(fams.items()):
        out += [round(v["tokens"] / tot, 6), None]  # prefix filled per arm below
        out[-1] = fam
    # fix rounding residue onto the largest family, as blend_weights.py does
    ws = [out[i] for i in range(0, len(out), 2)]
    residue = round(1.0 - sum(ws), 6)
    big = max(range(len(ws)), key=lambda i: ws[i])
    out[2 * big] = round(ws[big] + residue, 6)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pools", type=Path, default=Path(POOL_ROOT) / "pools_5b.json")
    a = ap.parse_args()
    acct = json.loads(a.pools.read_text())
    base_text = BASE.read_text()
    base = yaml.safe_load(base_text)
    written = []
    for arm, pool in ARMS.items():
        key = "filtered" if arm == "filtered_k2" else "control"
        b = blend(acct[key])
        data_path = []
        for i in range(0, len(b), 2):
            data_path += [b[i], f"{POOL_ROOT}/{pool}/{b[i + 1]}/tokenized_base_input_document"]
        for seg, exit_iter in SEGMENTS:
            cfg = yaml.safe_load(base_text)
            cfg["dataset"]["data_path"] = data_path
            cfg["dataset"]["path_to_cache"] = f"{CACHE_ROOT}/control_pretraining_longmino_5b_{arm}"
            cfg["train"]["train_iters"] = TRAIN_ITERS
            if exit_iter is not None:
                cfg["train"]["exit_interval"] = exit_iter
            else:
                cfg["train"].pop("exit_interval", None)
            cfg["scheduler"]["lr_wsd_decay_iters"] = TRAIN_ITERS
            d = f"{CKPT_ROOT}/control_pretrain_30b_baseline_longmino_5b_{arm}"
            cfg["checkpoint"]["load"] = d
            cfg["checkpoint"]["save"] = d
            cfg["checkpoint"]["save_interval"] = TRAIN_ITERS
            cfg["logger"]["wandb_exp_name"] = f"control_pretrain_30b_baseline_longmino_5b_{arm}"
            name = f"nemotron_nano_30b_baseline_longmino_5b_{arm}_seg{seg}.yaml"
            hdr = (f"# GENERATED by make_5b_configs.py from {BASE.name} — do not edit by hand.\n"
                   f"# Arm {arm} ({pool}), segment {seg}: train_iters {TRAIN_ITERS}, "
                   f"{'exit_interval ' + str(exit_iter) if exit_iter else 'runs to the end'}; "
                   f"see the module docstring for the stated diff from the 20B config.\n")
            (HERE / name).write_text(hdr + yaml.safe_dump(cfg, sort_keys=False, width=120))
            written.append(name)
    print("\n".join(written))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
