dataset:
  seq_length: 16384
  seed: 1234
  packed_sequence_specs:
    packed_sequence_size: 16384


train:
  micro_batch_size: 1
  gradient_accumulation_steps: 1
  train_iters: 100

optimizer:
  name: adamw
  lr: 8.0e-05
  min_lr: 0.0
  weight_decay: 0.01
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-08
  clip_grad: 1
  use_distributed_optimizer: true
  bf16: true

scheduler:
  lr_decay_style: cosine
  lr_warmup_fraction: 0.05

model:
  pipeline_model_parallel_size: 1
  tensor_model_parallel_size: 1
  expert_model_parallel_size: 4
  context_parallel_size: 2
  sequence_parallel: False

  gradient_accumulation_fusion: False
  recompute_granularity: full
  recompute_method: uniform

checkpoint:
  load: /projects/a5k/public/checkpoints/megatron_bridges/models/NVIDIA-Nemotron-3-Nano-30B-A3B-Base-BF16
  finetune: true
  save: /projects/a5k/public/checkpoints/megatron/nemotron_nano_dolci_instruct_sft_test
  save_interval: 0
  async_save: true

logger:
  timing_log_level: 2
  wandb_project: megatron-bridge-isambard
  wandb_exp_name: nemotron_nano_dolci_instruct_sft_test
